services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    networks:
      - inception
    restart: always
    ports:
      - 443:443
    volumes:
      - type: bind
        source: /home/junkpark/data/wordpress
        target: /var/www/html
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    networks:
      - inception
    restart: always
    expose:
      - 9000
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: /home/junkpark/data/wordpress
        target: /var/www/html
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    networks:
      - inception
    restart: always
    expose:
      - 3306
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: /home/junkpark/data/mariadb
        target: /var/lib/mysql

networks:
  inception:
    driver: bridge
