services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    networks:
      - inception
    restart: always
    ports:
      - 443:443
    volumes:
      - /home/junkpark/data/wordpress:/var/www/html:rw
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    networks:
      - inception
    restart: always
    expose:
      - 9000
    env_file:
      - ./.env
    volumes:
      - /home/junkpark/data/wordpress:/var/www/html:rw
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    networks:
      - inception
    restart: always
    expose:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - /home/junkpark/data/mariadb:/var/lib/mysql:rw

networks:
  inception:
    driver: bridge
