services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    expose:
      - 9000
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db
  db:
    container_name: db
    build: ./requirements/mariadb
    restart: always
    expose:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
