services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    expose:
      - 9000
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
  ftp:
    build: ./requirements/ftp
    image: ftp
    restart: always
    ports:
      - 20:20
      - 21:21
      - 21100-21110:21100-21110
    env_file:
      - ./.env
    volumes:
      - wordpress:/home
    depends_on:
      - wordpress
  redis:
    build: ./requirements/redis
    image: redis
    restart: always
    expose:
      - 6379:6379
    volumes:
      - redis:/data
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    restart: always
    expose:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  wordpress:
  mariadb:
  redis:
